### ISSUE TITLE
Avoid multiple calls of registerDeviceToken

### ISSUE THREAD

**Issue by LinusGeffarth** [pusher/push-notifications-swift#100]
Like suggested by the framework, we should avoid multiple calls of `registerDeviceToken`. However, I cannot find a way to determine whether this device has already been registered.  
I could manually save whether I've subscribed this device in user defaults, but 1. this wouldn't work after a reinstall and 2. would be very un-elegant.

I suggest adding a computed property to the framework, that does the whole user defaults thing as a workaround for now:

```swift
var isDeviceRegistered: Bool
```

Then, in AppDelegate, we could do:

    pushNotifications.start(instanceId: "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
    if !pushNotifications.isDeviceRegistered {
        pushNotifications.registerForRemoteNotifications()
    }
    try? pushNotifications.subscribe(interest: "xxx")

**Comment by LinusGeffarth** [comment]
Great. Thank you!

BTW, I **LOVE** Pusher / Beam.  
Most of the times, when a product page says "get started within 5 minutes" it takes way longer and I'm like "yeah, whatever".  
I went through the Quickstart and it literally took me 5 minutes and my mind was blown!  
So thanks so much for this service.

**Comment by lukabratos** [comment]
Hi @LinusGeffarth 

This should be fixed in the SDK version [2.0.0](https://github.com/pusher/push-notifications-swift/blob/master/CHANGELOG.md#200---2019-04-12).

I'm closing this issue for now but feel free to continue conversation if you would like to add anything.

Thanks!
