### ISSUE TITLE
Compile error - EventTypeHandler has no member getNotificationEventType

### ISSUE THREAD

**Issue by saferoom-app** [pusher/push-notifications-swift#101]
Hi,

We are trying to integrate PushNotifications Cocoa pod into Objective-c projects, all seems good, but we get this compile error all the time:
<img width="1023" alt="screenshot 2019-01-17 at 10 32 00" src="https://user-images.githubusercontent.com/21174174/51308876-70da5a80-1a43-11e9-9917-9f9854e0af00.png">

I guess we should turn on some flag, but which?

Thanks for help,
Ilia

**Comment by lukabratos** [comment]
Hi 👋 

In order to better understand what the problem could be, can you provide the following information:

- Which Xcode version are you using? 
- Which Swift language version are you using? You can check this [here](https://stackoverflow.com/a/46080904).

**Comment by saferoom-app** [comment]
Hello,

Sorry for missing that info. Here it is attached.
- SDK is v.1.1.0
- Xcode 10.1 (10B61)

<img width="626" alt="screenshot 2019-01-17 at 14 45 58" src="https://user-images.githubusercontent.com/21174174/51322793-b9573f80-1a66-11e9-8699-495e0ccb47c7.png">
<img width="527" alt="screenshot 2019-01-17 at 14 46 09" src="https://user-images.githubusercontent.com/21174174/51322800-bceac680-1a66-11e9-9c33-b22c65ce9936.png">

Cheers,
Ilia

**Comment by lukabratos** [comment]
Hi

Thanks. I've tested with the exactly the same version of the Xcode and version of the SDK and it successfully compiles.

Would it be possible to share this project with me so I can test it? You can send me an email to luka@pusher.com

If not, can you try and integrate the SDK into a fresh, new project and test if that works for you?

**Comment by saferoom-app** [comment]
Hi,

Same thing here - I've created a sample project and it compiles without any issues. So I guess it is a project problem. I will try to integrate to another app with existing project, let's see. 

One thing I've noticed that it asks me to convert to Swift 4.2 and then gives a compile error. I've tried:
- clean folder - same error.
- delete Derived Data, clean project -same error
- delete Derived Data, clean project, closed totally Xcode, opened again - same error.

<img width="355" alt="screenshot 2019-01-17 at 22 47 38" src="https://user-images.githubusercontent.com/21174174/51351290-c0a03c80-1aaa-11e9-8a1b-ffdca33d2adb.png">

Sorry, I can't share original project.

Cheers,
Ilia

**Comment by lukabratos** [comment]
Hey Ilia

The warning about the conversion can be ignored. It's not related to the issue.
Let me know if it works with another project.

I would like to reproduce the issue but I'm unable to.
Just to confirm again with you:
- You've integrated Beams iOS SDK version `1.1.0` into a project which is completely written in Objective-C and only dependencies contain Swift code? Or do you use Objective-C and Swift in your project?
- You're using Xcode version `10.1 (10B61)`
- What is the minimum iOS deployment target that is set in the project?
- Any other information that I might find helpful to identify the issue in your project?

Hopefully we can sort it out 👍

**Comment by lukabratos** [comment]
Hey

Great news, I'm glad that you've managed to resolve the issue 🎉 
If you'll have any other questions feel free to join our [Pusher Community Slack](https://feedback-beta.pusher.com).
