### ISSUE TITLE
Can you please list the steps to integrate the Pusher library manually?

### ISSUE THREAD

**Issue by funkyboy** [pusher/push-notifications-swift#108]
I mean, not using CocoaPods nor Carthage.
Thanks :)

**Comment by luismfonseca** [comment]
We recommend that our customers use package managers to manage dependencies. We want them to be and keep up-to-date without much hassle. As such, we won't provide instructions for manual installation -- although we don't prevent anyone from actually doing it ;).

Thanks for understanding.
