### ISSUE TITLE
This copy of libswiftCore.dylib requires an OS version prior to 12.2.0

### ISSUE THREAD

**Issue by Velissel** [pusher/push-notifications-swift#112]
I am working on a React Native project with EMBEDDED_CONTENT_CONTAINS_SWIFT set to YES and SWIFT_VERSION set to 5.0 in pod file like below

`pod 'PushNotifications', '~> 1.3'`

```
targets = ['PushNotifications']

if targets.include? target.name
  target.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '5.0'
  end
end
```

It works perfect, but does not work with iOS 12.2. Running on iOS 12.2 causes 'This copy of libswiftCore.dylib requires an OS version prior to 12.2.0' and crashes

Does anyone have idea of it?

Cheers

**Comment by lukabratos** [comment]
Hi @Velissel 

We don't officially support React Native at the moment.

I would advise that you check list of issues on the official React Native repo citing the problem that you're experiencing.

I'm closing this issue for now but feel free to continue conversation if you would like to add anything.

Thanks!
