### ISSUE TITLE
Swift 5 compatability

### ISSUE THREAD

**Issue by thirdmanrecords** [pusher/push-notifications-swift#115]
I am getting a Command CompileSwift failed with a non zero exit code on version 2.0.1 when attempting to compile on Swift 5. The StarScream dependency is also failing with the same error. It looks like PushNotifications is pulling in version Starscream (3.0.6). It looks like Swift 5 compatibility was introduced in Starscream 3.1.0.

**Comment by lukabratos** [comment]
Hi @thirdmanrecords 

> It looks like PushNotifications is pulling in version Starscream (3.0.6)

Where can you see this? Can you share the error message or logs with me please?
`push-notifications-swift` SDK doesn't rely on StarScream AFAIK.

**Comment by thirdmanrecords** [comment]
Sorry, I mis-read the Pod dependency. PusherSwift relies on it and is using incorrect version. I will add an issue there. Are we still waiting for PushNotifications Swift 5 compatibillity though?

**Comment by lukabratos** [comment]
> Are we still waiting for PushNotifications Swift 5 compatibillity though?

PushNotifications SDK builds correctly with Swift 5.
