### ISSUE TITLE
Cartfile versioning?

### ISSUE THREAD

**Issue by suragch** [pusher/push-notifications-swift#117]
Shouldn't the cartfile have a version number added to it?

So instead of this:

```
github "pusher/push-notifications-swift"
```

It would have something like this:

```
github "pusher/push-notifications-swift" ~> 1.0
```

**Comment by lukabratos** [comment]
By not specifying the version number it means that it will use the latest version available.
You can also specify a specific version if you would like to. You can read more about the use cases [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#example-cartfile).
