### ISSUE TITLE
Fatal error: Can't remove first element from an empty collection

### ISSUE THREAD

**Issue by JoeyLeeMEA** [pusher/push-notifications-swift#121]
PushNotifications.swift : 28

```
if let completion = self?.userIdCallbacks[userId]?.removeFirst() {
```

it seems sometimes calling `removeFirst()` to an empty array and encountered the error.

I am using PushNotifications (2.1.0)

**Comment by lukabratos** [comment]
Hi @JoeyLeeMEA 

Thank you very much for reporting this issue and apologies for the inconvenience.
Please update the SDK to the version `2.1.2`. Issue should be resolved.

Thank you.
