### ISSUE TITLE
Parsing token in a different JSON object format

### ISSUE THREAD

**Issue by mmdev1** [pusher/push-notifications-swift#147]
Can we have a way to parse a token in a different JSON object format? like below:  
```
"data": {
        "id": "12345",
        "type": "beam-token",
        "attributes": {
            "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMTc4NyIsImV4cCI6MTU"
        }
    }
```
as conformance to https://jsonapi.org

**Comment by luismfonseca** [comment]
Why do you want to parse the token? It should be an opaque string from the client perspective.
