### ISSUE TITLE
error: unexpected non-void return value in void function (ServerSyncEventHandler and ServerSyncProcessHandler)

### ISSUE THREAD

**Issue by snadal** [pusher/push-notifications-swift#150]
When building an app that uses PushNotifications pod, I get the following compiler error messages:

    /Users/vagrant/git/ios/Pods/PushNotifications/Sources/ServerSyncEventHandler.swift:11:24: error: unexpected non-void return value in void function
                    return handler
                           ^~~~~~~
    /Users/vagrant/git/ios/Pods/PushNotifications/Sources/ServerSyncEventHandler.swift:15:24: error: unexpected non-void return value in void function
                    return handler
                           ^~~~~~~
    /Users/vagrant/git/ios/Pods/PushNotifications/Sources/Internal/ServerSyncProcessHandler.swift:9:24: error: unexpected non-void return value in void function
                    return handler
                           ^~~~~~~
    /Users/vagrant/git/ios/Pods/PushNotifications/Sources/Internal/ServerSyncProcessHandler.swift:13:24: error: unexpected non-void return value in void function
                    return handler
                           ^~~~~~~

This happens also with the quickstart application for Chatkit

 sh -c "$(curl -fsSL https://raw.githubusercontent.com/pusher/chatkit-quickstart-swift/dashboard/chatkit-quickstart-install.sh)" v1:us1:[instance locator]

This prevents from using PushNotifications pods on CI systems like Bitrise. Any hints?

**Comment by luismfonseca** [comment]
Please try the very latest version of SDK (3.0.2) as it should fix this.

Let me know how that goes.

**Comment by luismfonseca** [comment]
Closing for now, but let us know if it doesn't work out!

**Comment by snadal** [comment]
Yes! It worked, thanks so much!
