### ISSUE TITLE
Network error: Device Not Found

### ISSUE THREAD

**Issue by LinusGeffarth** [pusher/push-notifications-swift#153]
After upgrading from 1.x.x to 3.0.4, I am seeing the following error:

> [PushNotifications]: Network error: Device Not Found

My setup in the `AppDelegate` is as follows:

```swift
let pushNotifications = PushNotifications.shared
pushNotifications.start(instanceId: "<id retracted>")
try? pushNotifications.addDeviceInterest(interest: "info")
if isInDebugMode {
    try? pushNotifications.addDeviceInterest(interest: "debug")
}
pushNotifications.registerForRemoteNotifications()
```

Am I missing something?

**Comment by jonathanlloyd** [comment]
Hi,
Sorry for taking so long to reply. If you're still having issues, could you send any details to support@pusher.com & we'll help you debug further.

Thanks!
