### ISSUE TITLE
Notifications not arriving

### ISSUE THREAD

**Issue by LinusGeffarth** [pusher/push-notifications-swift#155]
I've set up everything on my backend and my iOS app and was able to send notifications to both users and interest groups.  
In my iOS app, I run `.start`, `.addDeviceInterest`, `.registerForRemoteNotifications` and `.registerDeviceToken`.  

However, today, it stopped working **on my iPad**. It is still working on my iPhone – with the exact same build. (And yes, I have allowed notifications for the app on my iPad.)

When sending a test notification from the dashboard (or through my backend), I see the log for the notification (w/ publish-id) confirming it was sent successfully. The logs also show my device being authenticated. Still, no notification arrives.

<img width="1145" alt="Bildschirmfoto 2020-02-17 um 14 21 51" src="https://user-images.githubusercontent.com/9455439/74657589-d93cc380-5190-11ea-9de5-6ee11e30fb78.png">

I have:
- created & added development & production certificates for my app for push notifications
- restarted Xcode and my iDevice
- deleted & reinstalled the iOS app
- updated push-notifications-swift to 3.0.4

What can I do?

**Comment by jonathanlloyd** [comment]
Hi @LinusGeffarth, sorry to see you're having issues. Please could you forward this to support@pusher.com? It'll be easier to help debug this over email & we can open another issue here if it turns out to be a bug in the SDK.

Thanks!

**Comment by ben-pusher** [comment]
Just to close the loop on this one for anyone who comes across this in the future - @LinusGeffarth has managed to resolve this issue by switching to a different network. 



Seriously. 

Here's an [SO discussion](https://stackoverflow.com/a/34332047/3397217) of the issue, while Apple actually have a [support article](https://support.apple.com/en-us/HT203609) for this

Props to Linus for figuring this out!
