### ISSUE TITLE
The app crashes on iPhone SE (2nd) device.

### ISSUE THREAD

**Issue by DatNDIOS** [pusher/push-notifications-swift#179]
Hey Pusher,

I am using release version 4.0.0.
I tried to open the app and got the problem as below:

<img width="1318" alt="Screen Shot 2021-09-09 at 4 02 05 PM" src="https://user-images.githubusercontent.com/61822428/132660142-45f6d162-cc84-4c4e-8d19-f283c40fc0e1.png">
<img width="1146" alt="Screen Shot 2021-09-09 at 3 58 54 PM" src="https://user-images.githubusercontent.com/61822428/132660166-ff0a9d76-dcab-4e98-8704-d4aec7e66bec.png">
<img width="1395" alt="Screen Shot 2021-09-09 at 3 59 11 PM" src="https://user-images.githubusercontent.com/61822428/132660180-ba179078-86b5-404c-94b1-80bad9c6492c.png">

I don't know why this error occurs?

**Comment by benw-pusher** [comment]
Could you check if you are interacting with the library from outside the main thread? 
What is the code that is spawning this error?

**Comment by DatNDIOS** [comment]
I had a crash as soon as when I open the app.

> What is the code that is spawning this error?

Did calling multiple `addDeviceInterest` cause the error?

<img width="690" alt="Screen Shot 2021-09-09 at 6 31 28 PM" src="https://user-images.githubusercontent.com/61822428/132678404-89526b3e-82da-4f01-9900-605727a1e637.png">
<img width="643" alt="Screen Shot 2021-09-09 at 6 32 17 PM" src="https://user-images.githubusercontent.com/61822428/132678420-0be7186b-4786-4064-b0b2-fd34a5c7d1cc.png">
<img width="897" alt="Screen Shot 2021-09-09 at 6 24 38 PM" src="https://user-images.githubusercontent.com/61822428/132677839-4378ccaa-c196-4bef-867f-628fa34306bd.png">

**Comment by benw-pusher** [comment]
Calling `addDeviceInterest` multiple times should not cause this behaviour. 

Do you know which line of the code you have shared is causing this error? Has the `PushNotifications.shared.start()` and `registerForRemoteNotifications` completed and the error thrown when setting device interests?
Is the error intermittent or does it occur each time?

**Comment by DatNDIOS** [comment]
@benw-pusher 
Sorry for the late reply.
Currently, I can use the app normally.
So I'll close this issue.
Thanks for your support!
