### ISSUE TITLE
Crash on addDeviceInterest

### ISSUE THREAD

**Issue by paul-homie** [pusher/push-notifications-swift#180]
We are getting a decent amount of crashes on calling addDeviceInterest.

I see in `PushNotificationsStatic` on line 196 you have this code:
`fatalError("PushNotifications.shared.start must have been called first")`

Why must you use fatalError? It looks like there is an edge case where we accidentally call `addDeviceInterest` without calling `start`. Couldn't this just be ignored if start isn't called?

**Comment by paul-homie** [comment]
I see in `PushNotificationsStatic` on line 196 you have this code:
`fatalError("PushNotifications.shared.start must have been called first")`

Why must you use fatalError? It looks like there is an edge case where we accidentally call 'addDeviceInterest` without calling `start`. Couldn't this just be ignored if start isn't called? Must you really crash?

**Comment by benjamin-tang-pusher** [comment]
Could you catch this edge case before you call addDeviceInterest? For example use a boolean for if you’ve called start (similar to the private var startHasBeenCalledThisSession = false in Pusher).
