### ISSUE TITLE
Can't import PushNotifications into Objective-C

### ISSUE THREAD

**Issue by Gen98** [pusher/push-notifications-swift#181]
Hi,
I'm using [Cordova](https://cordova.apache.org/) to compile my web app into mobile app.

I have no problem using this framework before, but now I'm trying to integrate Pusher(Channels/Beams).

Following the [Official Docs](https://pusher.com/docs/beams/getting-started/ios/sdk-integration/), I can't "import PushNotifications",
I've tried with #import, @import but xCode says module not found
![image](https://user-images.githubusercontent.com/87834350/147978692-08123428-8c7a-4e55-b8db-833fee8a7330.png)

This is my PodFile
![image](https://user-images.githubusercontent.com/87834350/147978814-32058a9b-1c66-4c09-b5b0-931e7908f7eb.png)
In my workspace I can fin the pods installed by Carthage 
![image](https://user-images.githubusercontent.com/87834350/147979077-c8aba784-ac56-4a58-9e50-dd475e08609e.png)
And I have Added into "Link Binary..." section
![image](https://user-images.githubusercontent.com/87834350/147979140-0cc79e0d-0c0b-4da9-b2aa-8e2eb9decde5.png)

What am I missing? Thank you

**Comment by benjamin-tang-pusher** [comment]
Hi, we don't officially support Cordova, but with CocoaPods, you don't normally need to manually add a file to "Link Binary With Libraries" setting. For example my project has
<img width="647" alt="Screenshot 2022-02-10 at 16 50 19" src="https://user-images.githubusercontent.com/83954069/153456251-5ca3e5e7-014e-4207-8e26-5b5321eff9e2.png">
and
<img width="636" alt="Screenshot 2022-02-10 at 16 50 57" src="https://user-images.githubusercontent.com/83954069/153456247-6be78913-5b4b-48c7-a1ff-af1520b06375.png">
I couldn't see the second one in your screenshot. Is that missing from your project?
We also recommend `pod 'PushNotifications', '~> 4.0.0' `if possible.
