### ISSUE TITLE
Device could not be created

### ISSUE THREAD

**Issue by nicolas-vivot** [pusher/push-notifications-swift#182]
Hi,

We released an iOS app recently and are facing some issues to log in with Pusher Beams authenticated users.

Here is the process we apply when a user log into our application successfully:

- call the 'stop()' method on the SDK to potentially un subscribe a paste user that was logged in
- call our backend to get an authentication token. At this time, our backend is also deleting any Pusher user that has used the same device just to make sure that only the last logged user register on Pusher for that device.
- call the 'start()' method to start the pusher beams sdk
- call the 'setUserId()' method to register this device with the current logged user

When a user explicitely log out our application, we don't do anything since we want that user to be able to receive notification on the mobile application.
That's also the reason why we do this 'stop()' call first after a login, to clear the pusher SDK local state if the new logged user is different than the previous one.

Time to time, some users get errors while doing the 'setUserId()' operation with the following message:

**Device could not be created**

I believe this is an error returned by the Pusher backend itself, not the SDK.

For one of these users, i have checked on our backend the devices it get, and try to send notifications to his device with the Pusher debug console, but not user nor device were found on Pusher for the given Pusher User ID.

What does this error message means ? What could be the potential reasons ?

Note: please confirm here whether this is more a server side pusher issue than an SDK one.

**Comment by benjamin-tang-pusher** [comment]
Hi Nicolas,

We will provide troubleshooting advice on the Zendesk support ticket you raised earlier, please see that for updates.

**Comment by nicolas-vivot** [comment]
No update on the ticket for the last 20 days

**Comment by nicolas-vivot** [comment]
This has been recognized as a bug on the SDK, the fix would probably take 2 to 3 lines of code but there is still nothing...

@benjamin-tang-pusher When can this be fixed on the SDK (handling correctly the error returned by Pusher backend services) ?

**Comment by LinusGeffarth** [comment]
@nicolas-vivot did you/they figure this out? I'm always getting the same error message and your implementation (thanks for sharing) unfortunately didn't work for me.

**Comment by sefasenturk95** [comment]
@LinusGeffarth @nicolas-vivot  Any updates on this? I have the same problem.. Why is this issue closed? @benjamin-tang-pusher

**Comment by LinusGeffarth** [comment]
@sefasenturk95 unfortunately I never figured this out and went another route. It seems like Pusher is discontinued, sadly. Sorry!
