### ISSUE TITLE
[🐜 Bug Report] Xcode 15 fails to locate `PushNotifications.shared`

### ISSUE THREAD

**Issue by kcw-grunt** [pusher/push-notifications-swift#187]
## Problem
After installing the package per instructions, Xcode is unable to access the framework.

## Steps to recreate the issue

1. Added `https://github.com/pusher/push-notifications-swift/` package dependency
2. Added `import PushNotifications` to `App Delegate`
3. Added `let pushNotifications = PushNotifications.shared` to `App Delegate`

## Environment
Xcode 15.0.1
Swift version 4.2

| App Delegate showing error |
|----------------------------|
|<img width="1210" alt="Screenshot 2023-11-25 at 2 56 09 PM" src="https://github.com/pusher/push-notifications-swift/assets/2899463/4fb214c6-34eb-4e8c-b092-3a242479766b">|

**Comment by benw-pusher** [comment]
I'm not able to replicate the same. Could you share the podfile and podfile.lock? It could be that there is a conflict.

**Comment by kcw-grunt** [comment]
Thanks @benw-pusher  for looking.
Actually using the swift package not cocoapods 

I noted the docs dont explicit allow as a package but is was found in the Swift Package index/registry and we are not interesting in re-adding Cocoapods.  

Did you guys test with the SPM?

**Comment by benw-pusher** [comment]
I believe this s tested with SPM. Have you followed the [instruction here?](https://github.com/pusher/push-notifications-swift#swift-package-manager-dependency)

**Comment by kcw-grunt** [comment]
Hi @benw-pusher ,
Yes I have successfully installed the library into a few projects.

**Comment by benw-pusher** [comment]
Do all project experience the same issue or just this one?

**Comment by kcw-grunt** [comment]
No @benw-pusher just this one. My guess is the search paths are borked. But, I tried comparing the two and they seem to be the same.  The project is open source. Maybe you can see something obvious? 
https://github.com/litecoin-foundation/litewallet-ios

**Comment by kcw-grunt** [comment]
UPDATED:  @benw-pusher this was a case of name collision.
`PushNotifications` was already used in the codebase.
Refactored accordingly

Closing
