### ISSUE TITLE
Use of unresolved identifier 'Instance'

### ISSUE THREAD

**Issue by siempay** [pusher/push-notifications-swift#37]
I just installed it as in the README but I get this `Use of unresolved identifier 'Instance'` 
in the `@objc public final class PushNotifications: NSObject `

I use latest xcode 9 with swift 4 for and iOs app

**Comment by lukabratos** [comment]
Hi

Which version of the SDK are you using?

We have released version `0.10.0` 2h ago and it has some breaking API changes so some docs might be outdated.
Here's up to date example that works with `0.10.0`: [Link](https://github.com/pusher/push-notifications-swift/blob/master/push-notifications-ios/push-notifications-ios/AppDelegate.swift).

Let me know how it goes 👍

**Comment by siempay** [comment]
No, the error is coming from the pod itself, not from code I added. I mean a fresh installation is show error 
![capture d ecran 2018-02-13 a 16 34 56](https://user-images.githubusercontent.com/14646888/36161587-f9f82724-10db-11e8-8ab1-102edf93d96d.png)

**Comment by lukabratos** [comment]
@siempay thanks. I've identified the issue. I'll let you know once it's fixed.

**Comment by siempay** [comment]
I went back to 0.9.2 and its working fine

**Comment by lukabratos** [comment]
Hey

You can create Pusher Push Notifications instance here: https://dash.pusher.com/

**Comment by siempay** [comment]
ok one more question; Im getting this `The provider token is not valid or the token signature could not be verified.
`
sorry

**Comment by lukabratos** [comment]
Hi @siempay 

Can you try and integrate the version `0.10.0` again? Issue should be resolved.
Use: `pod install --repo-update`

Let me know, Luka.

**Comment by lukabratos** [comment]
This issue was resolved in version `0.10.0`.

**Comment by siempay** [comment]
`self.pushNotifications.register(instanceId: "*****-****-***-****-*******")`
the register function is not defined! 
I tried the `registerDeviceToken()` but it needed type `Data` and I have string ! 
what should I do?

**Comment by siempay** [comment]
ok so I did not have to add this line in `	func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool ` 
I just had to add it in 
`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) `

**Comment by lukabratos** [comment]
Hi

You're probably using version `0.10.1`, please refer to the updated docs [here](https://docs.pusher.com/push-notifications/reference/ios).

Issue related to `Instance` was resolved in version `0.10.0`.

**Comment by siempay** [comment]
ah ok I got theme

**Comment by sauryatechnologies** [comment]
I am getting error on InstanceID:
Swift Compiler Error: Use of unresolved identifier 'InstanceID'
