### ISSUE TITLE
Registering Instance ID issue after update.

### ISSUE THREAD

**Issue by NthnGnzls** [pusher/push-notifications-swift#62]
I am having an issue regarding the registration of instance id, any help would be appreciated. thanks!

<img width="763" alt="screen shot 2018-06-01 at 10 19 42 am" src="https://user-images.githubusercontent.com/24404359/40817534-784e8688-6585-11e8-8893-6bee423291cc.png">

**Comment by lukabratos** [comment]
Hi @NthnGnzls 

API has changed from `register` to `start` in the SDK version [`0.10.1`](https://github.com/pusher/push-notifications-swift/commit/344b9c15b1e74d55d87050a5b903f8b14f47eba3#diff-9e9aec3efcab9ee90576ccbc3b10a1faL26).

I would suggest that you update to the latest version, which is `0.10.7`
