### ISSUE TITLE
Include Carthage info to Readme

### ISSUE THREAD

**Issue by emilkarl** [pusher/push-notifications-swift#65]
These steps should not be left out from docs about Carthage. There also seems to be a need to specify `--platform ios` now otherwise its installed into `Build/Mac`.

https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

![image](https://user-images.githubusercontent.com/10711/41525762-5f911380-72e2-11e8-882c-46a14d175ac5.png)

**Comment by emilkarl** [comment]
Missing "Always embed swift libraries" 

<img width="519" alt="teamtailormobile xcodeproj 2018-06-18 11-11-38" src="https://user-images.githubusercontent.com/10711/41528093-5f443c2a-72e9-11e8-8912-e2b184c53337.png">

---

Also missing info about making *Framwork Search Paths* _recursive_ 

<img width="941" alt="monosnap 2018-06-18 11-06-00" src="https://user-images.githubusercontent.com/10711/41528105-68484726-72e9-11e8-8144-ab531ccfece6.png">

**Comment by lukabratos** [comment]
Hi @emilkarl 

That's interesting. I've ran `carthage update` and it generated two folders; one for iOS and another one for Mac. Which version of Carthage are you using?

Our SDK supports both platforms (iOS, Mac) so it would be incorrect to specify platform just as `--platform ios`.

Thanks for your feedback, I will take your thoughts into consideration.

**Comment by emilkarl** [comment]
Mine did not create `iOS`, only mac if I did not specify platform like that? Strange. @lukabratos

**Comment by alfonsosn** [comment]
Hey after following all the steps in 

https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

as well, as: https://docs.pusher.com/beams/ios/sdk-integration#install-from-carthage

I'm getting 'config.h' not found... Any thoughts on what this is about?

**Comment by moaxaca** [comment]
@emilkarl I had a similar issue, but after updating to xCode 10.0 (dangerous) I was able to get Carthage generating iOS and code signing working.

Here is a good reference for anyone else dealing with app store submission issues: 
https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos
http://www.openradar.me/radar?id=6409498411401216

I was receiving: Code signing "PushNotifications.framework" failed.
In the logs I had: /Root/Payload/openroads.app/Frameworks/PushNotifications.framework: code object is not signed at all

**Comment by aatalyk** [comment]
Hi @moaxaca, how did you solve the issue with App Store submission could you provide more info on this?

**Comment by moaxaca** [comment]
@aatalyk So my issue was really around following the install instructions in the master branch of this repo. They got me up and running for development but failed the signing process. Reference image below:

![screen shot 2018-11-11 at 9 31 16 am](https://user-images.githubusercontent.com/7247019/48316151-a3279180-e594-11e8-9792-2cde062d9a5f.png)

I eventually went back to the Carthage docs and read their installation instructions. Probably should have done that first X). 

Here is a reference:
https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

I simply added the correct build phase hooks, my configuration in an image below, and everything signed and submitted correctly. 

![screen shot 2018-11-11 at 9 33 17 am](https://user-images.githubusercontent.com/7247019/48316201-395bb780-e595-11e8-9522-fd9daf4d2302.png)

Hope this help!

**Comment by lukabratos** [comment]
I have updated the readme file with more detailed installation instructions, [here](https://github.com/pusher/push-notifications-swift/pull/99).
Hopefully this step by step guide from the official documentation will be enough to reduce the confusion.

Thanks for flagging this issue and apologies for any inconvenience caused.
