### ISSUE TITLE
How to unregisterForRemoteNotifications ?

### ISSUE THREAD

**Issue by EllisShen** [pusher/push-notifications-swift#81]
Hi pusher team,

In the user guide, it describes the procedure of setup Pusher, and use the client API to register to receive remote notifications via APN. 
```
PushNotifications.shared.registerForRemoteNotifications()
```
But, how do I *unregister* the service? Is there a way to do this via the Pusher API?
My case is that a few devices failed to receive notifications after restoring a backup image to another phone. I think the solution is to unregister the service and register again.

**Comment by lukabratos** [comment]
Hi @EllisShen 

Currently we don't support this functionality yet but it's scheduled to be implemented in one of our next iterations. I will follow back with you once it's done.

**Comment by EllisShen** [comment]
@lukabratos 

Thank you for getting back to me. Ok, please keep posting me when the feature is ready. For now, can I simply call apple API ```func unregisterRemoteNotifications()``` to reset the service with Pusher?

**Comment by EllisShen** [comment]
@lukabratos  any update of this feature request? 
Our users are reporting the problem of unable to receive any notification after restoring the image from iCloud.  I've tried many ways but no solution is workable. Do you have ETA of Pusher's unregister function?

**Comment by lukabratos** [comment]
Hi Ellis

Can you please message me on my email please?
It's my first name @ pusher.com

Thanks!

**Comment by EllisShen** [comment]
Hi @lukabratos 

Thanks for the notice. I've sent the email to you, please check it.

**Comment by lukabratos** [comment]
We're working on this issue: #90

**Comment by lukabratos** [comment]
Hi @EllisShen 

This is possible in the SDK version [2.0.0](https://github.com/pusher/push-notifications-swift/blob/master/CHANGELOG.md#200---2019-04-12).

Please see the docs, [here](https://pusher.com/docs/beams/reference/ios#-clearallstate).

Thanks!
