### ISSUE TITLE
Suggestion: Increment badge counter

### ISSUE THREAD

**Issue by emilkarl** [pusher/push-notifications-swift#89]
I'm not really sure about this and if it is even possible. 

It would be awesome to be able to set `incrementBadge: true` when publishing notifications and in this code you could use `applicationIconBadgeNumber` to increment current badge number with 1 for every notification you get with this flag set to true. In that case notifications to increment badge count without starting the app.

We're building with React Native and we could access this in the JS code but we cannot update the badge count from the JS code until the app is started.

**Comment by emilkarl** [comment]
Made a PR for the React Native lib instead. https://github.com/b8ne/react-native-pusher-push-notifications/pull/30

**Comment by lukabratos** [comment]
Hey @emilkarl 

Is this issue still relevant? I've noticed that your PR was merged in the RN SDK.

**Comment by emilkarl** [comment]
I guess not.
