### ISSUE TITLE
Array+CalculateMD5 - Optional string not unwrapped 

### ISSUE THREAD

**Issue by BenitoP** [pusher/push-notifications-swift#91]
Good day,

Just installed the Pusher Beams pod via the Pusher website as per the instructions. I am still receiving the `Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?` error in the file Array+CalculateMD5.swft. I see there was a fixed pushed for this 2 months ago though although the problem still persist. I have reinstalled a couple of times, cleaned the project but still no luck.

![screen shot 2018-09-11 at 14 27 05](https://user-images.githubusercontent.com/5366186/45360123-eb472980-b5ce-11e8-82fe-94e690ac0d8f.png)

**Comment by lukabratos** [comment]
Hey @BenitoP 

Our SDK supports Swift 4. I believe that you're getting this error because you're using Swift 3 in your project.
If you can I would advise you to update to Swift 4. [Here](https://stackoverflow.com/a/46808111) are the detailed instructions on how you can do that.

**Comment by BenitoP** [comment]
@lukabratos Thanks! Fixed the issue by just setting the project to Swift 4 and updating the pods!
